** latex build
#+begin_src bash
  cd latex
  pdflatex main.tex
#+end_src

** First e-mail
Dear all,

I hearby propose to continue Mike's legacy of Swedish Mondays!

If you are a complete beginer, or that you have some bases, or intermediate
level or even speak fluently (we will need some), you are all very welcome to
join. The goal is to speak Swedish, obviously, but also to learn at every
levels.

We will take some of the subjects that mike created, to begin with at least,
subjects like: films, series, books, video games, your experience with sweden
like your favorite places, swedes, how it is to live abroad (or not), and funny
discutions about aliens and space, housepets, and we can later continue by
finding new subjects to explore.

I propose as the first meeting a presentation of yourself or the
country/region/city you'r originally from. You will find a form attached to this
email with the bases of how you could say all this in Swedish. If you're not
comfortable enough yet so speak swedish, you can start small with a few
sentences, and we will be happy to help you out translating the rest because
this is the goal of course, to learn together.

The more we are, the funnier it will get. We can begin with a few sessions
before everyone goes to summer vacations, and then set a weekly session
afterwards.

The first lunch will be on the 8 or 15 of Jun, depending on the disponibility of
everyone.

Happy to see you soon for learning in a good a convivial setting!

** First email 2
Swedish Mondays - The Return, Continuing Mike's Legacy

Dear all,

I'd like to propose continuing Mike's legacy of Swedish Mondays!

Whether you're a complete beginner, have some basic knowledge, have an
intermediate level, or already speak Swedish fluently (we'll definitely need
some fluent speakers!), you're all very welcome to join. The goal is to practice
speaking Swedish, but also to learn together at every level.

To get started, we can use some of the topics Mike introduced, such as films, TV
series, books, video games, your experiences in Sweden, favorite places,
cultural differences, what it's like to live abroad (or not), and fun
discussions about topics like space, aliens, pets, and more. As we go along, we
can add new subjects based on everyone's interests.

For our first meeting, I suggest that everyone briefly presents themselves or
talks about the country, region, or city they come from. I've attached a simple
guide with some useful Swedish phrases that can help you prepare. If you don't
yet feel comfortable speaking entirely in Swedish, that's perfectly fine. You
can start with a few sentences, and we'll be happy to help translate and support
you along the way. After all, the purpose is to learn together.

The more people join, the more fun the sessions will be!

I'm proposing the first lunch session on September 21st, and then establishing a
regular weekly session afterwards.

I look forward to seeing you there and learning together in a friendly and
welcoming atmosphere!

** versions
*** 2024
- 3 - Gott nytt år! Vad gjorde ni under julen?
- 4 - Din upplevelse i Sverige!
- 5 - Böcker och att läsa!
- 6 - Datorspel!
- 7 - Hur är svenskar?
- 8 - Rymden och Utomjordingar!
- 9 - Din bästa semester!
- 11 - Växter och husdjur!
- 12 - Kläder och stil!
- 13 - Olika sätt att resa!
- 16 - Att bo utomlands!
- 17 - Att bo utomlands!
- 18 - Teknik och människor!
- 19 - Jobb och arbete!
- 21 - Hobbies och fritid!
- 23 - Språk och kommunikation!
- 38 - Sommarminnen!
- 39 - När hösten kommer
- 40 - När hösten kommer
- 42 - Matvanor
- 44 - Matvanor
- 45 - Resor och Platser att Besöka
- 46 - Helgplaner
- 47 - Att Hålla Kontakt
- 48 - Filmer och Serier
- 49 - Advent
- 50 - Favoritplatser i Sverige

*** 2025
- 5 - Vad gjorde du under julen?
- 6 - Resor och Semester
- 7 - Mina Intressen
