** latex build
#+begin_src bash
  cd latex
  pdflatex main.tex
#+end_src

** First email
Dear all,

I'd like to propose continuing Mike's legacy of Swedish Mondays!

Whether you're a complete beginner, have some basic knowledge, have an
intermediate level, or already speak Swedish fluently (we'll definitely need
some fluent speakers!), you're all very welcome to join. The goal is to practice
speaking Swedish, but also to learn together at every level.

To get started, we can use some of the topics Mike introduced, such as films, TV
series, books, video games, your experiences in Sweden, favorite places,
cultural differences, what it's like to live abroad (or not), and fun
discussions about topics like space, aliens, pets, and more. As we go along, we
can add new subjects based on everyone's interests.

For our first meeting, I suggest that everyone briefly presents themselves or
talks about the country, region, or city they come from. I've attached a simple
guide with some useful Swedish phrases that can help you prepare. If you don't
yet feel comfortable speaking entirely in Swedish, that's perfectly fine. You
can start with a few sentences, and we'll be happy to help translate and support
you along the way. After all, the purpose is to learn together.

The more people join, the more fun the sessions will be!

I'm proposing the first lunch session on September 21st in E:4130 (4th floor,
LUCAS room), and then establishing a regular weekly session afterwards.

I look forward to seeing you there and learning together in a friendly and
welcoming atmosphere!

-- Félix

** Later meetings
Swedish Pronunciation Guide:
https://svenskaspeak.speaklangs.com/swedish-pronunciation.html

** versions
*** 2024
- 3 - Gott nytt år! Vad gjorde ni under julen?
- 4 - Din upplevelse i Sverige!
- 5 - Böcker och att läsa!
- 6 - Datorspel!
- 7 - Hur är svenskar?
- 8 - Rymden och Utomjordingar!
- 9 - Din bästa semester!
- 11 - Växter och husdjur!
- 12 - Kläder och stil!
- 13 - Olika sätt att resa!
- 16 - Att bo utomlands!
- 17 - Att bo utomlands!
- 18 - Teknik och människor!
- 19 - Jobb och arbete!
- 21 - Hobbies och fritid!
- 23 - Språk och kommunikation!
- 38 - Sommarminnen!
- 39 - När hösten kommer
- 40 - När hösten kommer
- 42 - Matvanor
- 44 - Matvanor
- 45 - Resor och Platser att Besöka
- 46 - Helgplaner
- 47 - Att Hålla Kontakt
- 48 - Filmer och Serier
- 49 - Advent
- 50 - Favoritplatser i Sverige

*** 2025
- 5 - Vad gjorde du under julen?
- 6 - Resor och Semester
- 7 - Mina Intressen
